### ISSUE TITLE
Propose database schema for storing comments

### ISSUE THREAD

**Issue by pjeziorowski** [appwish/commentservice#6]
## Requirements
- we should be able to store 'threaded comments' - users should be able to reply to a comment
- design and propose a database schema that will do this efficiently (a tree structure?)

**Comment by muruganmscit** [comment]
Team, started working on schema design.

**Comment by pjeziorowski** [comment]
Great :) This one (comments) is one of the trickiest to design in what we have in plans at the moment in my opinion so good luck & have fun :D
