### ISSUE TITLE
Implement CRUD operations on comments

### ISSUE THREAD

**Issue by pjeziorowski** [appwish/commentservice#7]
## Requirements
- we should be able to store, read, update and delete comments
- create repositories that are capable of doing CRUD operations on comments

Here you have database schema designed in one of previous tasks: https://github.com/appwish/commentservice/blob/master/docs/database/CommentSchemaDesign.md

**Comment by muruganmscit** [comment]
will be start on this issue start today.

**Comment by pjeziorowski** [comment]
done
